In [0]:
import numpy as np

In [39]:
match_award=int(input("Enter a match_award Value \t"))
gap_penalty=int(input("Enter a gap_penalty Value \t"))
mismatch_penalty=int(input("Enter a mismatch_penalty Value \t"))

Enter a match_award Value 	2
Enter a gap_penalty Value 	-1
Enter a mismatch_penalty Value 	-2


In [40]:
seq_s=input("Enter a 1st sequence \t")
seq_t=input("Enter a 2nd sequence \t")

Enter a 1st sequence 	GGTTGACTA
Enter a 2nd sequence 	TGTTACGG


In [0]:
def match_score(x,y):
    if x=='-' or y=='-':
        return gap_penalty
    elif x==y:
        return match_award
    else:
        return mismatch_penalty

In [62]:
def needleman_wunsch(seq_s, seq_t):
   
    m=len(seq_s) #length 1st sequence
    n=len(seq_t) #length 2nd sequence
    V=np.zeros((m+1,n+1),dtype=int)    #zeros matrix
    
    for i in range(1,m+1):             #for column
        V[i][0]=gap_penalty*i
     
    for j in range(1,n+1):             #for row
        V[0][j]=gap_penalty*j
    
    for i in range(1,m+1):              #nested loop
        for j in range(1,n+1): 
            match=V[i-1][j-1]+match_score(seq_s[i-1],seq_t[j-1])         #for diagonal
            delete=V[i-1][j]+gap_penalty                       #for top 
            insert=V[i][j-1]+gap_penalty                        #for left
            V[i][j]=max(match,delete,insert)      #for max score

    return V
    

print(np.matrix(needleman_wunsch(seq_s,seq_t)))

 

[[ 0 -1 -2 -3 -4 -5 -6 -7 -8]
 [-1 -2  1  0 -1 -2 -3 -4 -5]
 [-2 -3  0 -1 -2 -3 -4 -1 -2]
 [-3  0 -1  2  1  0 -1 -2 -3]
 [-4 -1 -2  1  4  3  2  1  0]
 [-5 -2  1  0  3  2  1  4  3]
 [-6 -3  0 -1  2  5  4  3  2]
 [-7 -4 -1 -2  1  4  7  6  5]
 [-8 -5 -2  1  0  3  6  5  4]
 [-9 -6 -3  0 -1  2  5  4  3]]


In [47]:
def needleman_wunsch(seq_s, seq_t):
   
    m=len(seq_s) #length 1st sequence
    n=len(seq_t) #length 2nd sequence
    F=np.zeros((m+1,n+1),dtype=int)    # Generate zeros matrix to store scores   
    for i in range(1,m+1):             #for column
        F[i][0]=mismatch_penalty*i
     
    for j in range(1,n+1):             #for row
        F[0][j]=mismatch_penalty*j
    
    for i in range(1,m+1):              #nested loop
        for j in range(1,n+1): 
            match=F[i-1][j-1]+match_score(seq_s[i-1],seq_t[j-1])         #for diagonal
            delete=F[i-1][j]+mismatch_penalty                       #for top 
            insert=F[i][j-1]+mismatch_penalty                        #for left
            F[i][j]=max(match,delete,insert)      #for max score
    
# Traceback the alignment 
    alignA = ""
    alignB = ""
    i = m
    j = n
    opt_score=int(0)
    
    
    while i > 0 and j > 0:
        if F[i][j] == F[i-1][j-1] + match_score(seq_s[i-1], seq_t[j-1]):
            alignA += seq_s[i-1]
            alignB += seq_t[j-1]
           # opt_score+=match_score(seq_s[i-1],seq_t[j-1])
            i -= 1
            j -= 1

        elif F[i][j] == F[i-1][j] + mismatch_penalty:
            alignA += seq_s[i-1]
            alignB += '-'
            #opt_score+=opt_score+mismatch_penalty
            i -= 1

        elif F[i][j] == F[i][j-1] + mismatch_penalty:
            alignA += '-'
            alignB += seq_t[j-1]
            opt_score+=opt_score+mismatch_penalty
            j -= 1
            

    # Finish tracing up to the top left cell
    while j > 0:
        alignA += seq_s[j-1]
        alignB += '-'
        j -= 1
    while i > 0:
        alignA += '-'
        alignB += seq_t[i-1]
        i -= 1
    alignA = alignA[::-1]
    alignB = alignB[::-1]
    
    return(alignA, alignB)

output1, output2 = needleman_wunsch(seq_s, seq_t)

print(output1 + "\n" + output2)

#print("s" + alignA[::-1])
#print("s" + alignB[::-1])
#print(opt_score)
    

GGTTGACTA
TGTT-ACGG


NameError: ignored